#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 21 10:15:54 2018

@author: jpfeser
"""
import numpy as np
import tdtr

f = lambda x: np.array([x,x**2])
result = tdtr.romberg_integration(f,0,1,2)